version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql57
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    ports:
      - "3307:3306"
  app:
    restart: always
    container_name: rails_kinedu
    image: ror_260_524:master
    volumes:
      - ../:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    env_file:
      - ./.env
